#!/bin/usr/env python3
import boto3

sess = boto3.Session(region_name="us-east-1")
br = sess.client("bedrock")

models = br.list_foundation_models(byInferenceType="ON_DEMAND")
print("# This file is autogenerated")
print("from enum import Enum\n")
print("class Model(Enum):")

for m in models["modelSummaries"]:
    id = m["modelId"]
    print(
        f'    {id.upper().replace(".", "_").replace("-", "_").replace(":", "_")}="{id}"'
    )
