#!/bin/usr/env python3
import boto3

sess = boto3.Session(region_name="us-east-1")
br = sess.client("bedrock")

models_us_east = br.list_foundation_models()
sess = boto3.Session(region_name="us-west-2")
br = sess.client("bedrock")
models_us_west = br.list_foundation_models()

models = set(
    [
        m["modelId"]
        for m in models_us_east["modelSummaries"]
        if len(
            set(m["inferenceTypesSupported"]).intersection(
                ["ON_DEMAND", "INFERENCE_PROFILE"]
            )
        )
        > 0
    ]
)
models = models.union(
    [
        m["modelId"]
        for m in models_us_west["modelSummaries"]
        if len(
            set(m["inferenceTypesSupported"]).intersection(
                ["ON_DEMAND", "INFERENCE_PROFILE"]
            )
        )
        > 0
    ]
)


print("# This file is autogenerated")
print("from enum import Enum\n")
print("class Model(Enum):")

for id in sorted(models):
    print(
        f'    {id.upper().replace(".", "_").replace("-", "_").replace(":", "_")}="{id}"'
    )
